version: "3.8"
services:
  gopro-mysqldb:
    container_name: gopro-mysqldb
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gopro
      - MYSQL_USER=gopro
      - MYSQL_PASSWORD=root
    volumes:
      - ./docker/mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  gopro-backend:
    build: ./
    ports:
      - 8080:8080
    command: ["/app/gopro/web"] 
    environment:
      - DB_USER=gopro
      - DB_PASSWORD=root
      - DB_HOST=gopro-mysqldb
      - DB_PORT=3306
      - DB_NAME=gopro
      - JWT_SECRET=Wfu3FD9X5NcbST8e5S3hsgTpVAEGpJrFvnLrmDtsi6
    depends_on:
      - gopro-mysqldb
      - redis
    restart: always

  gopro-worker:
    build: ./
    command: ["/app/gopro/worker"] 
    environment:
      - DB_USER=gopro
      - DB_PASSWORD=root
      - DB_HOST=gopro-mysqldb
      - DB_PORT=3306
      - DB_NAME=gopro
      - JWT_SECRET=Wfu3FD9X5NcbST8e5S3hsgTpVAEGpJrFvnLrmDtsi6
    depends_on:
      - gopro-mysqldb
      - redis
    restart: always
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - gopro-backend
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  minio-gopro:
    image: minio/minio
    container_name: minio-gopro
    ports:
      - "9000:9000" # MinIO API port
      - "9001:9001" # MinIO Console port
    environment:
      MINIO_ROOT_USER: minioadmin       # Root user (access key)
      MINIO_ROOT_PASSWORD: minioadmin  # Root password (secret key)
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  grafana-data:
  minio-data: