version: "3.8"
services:
  gopro-mysqldb:
    container_name: gopro-mysqldb
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gopro
      - MYSQL_USER=gopro
      - MYSQL_PASSWORD=root
    volumes:
      - ./docker/mysql:/var/lib/mysql

  gopro-backend:
    build: ./
    ports:
      - 8080:8080
    environment:
      - DB_USER=gopro
      - DB_PASSWORD=root
      - DB_HOST=gopro-mysqldb
      - DB_PORT=3306
      - DB_NAME=gopro
      - JWT_SECRET=Wfu3FD9X5NcbST8e5S3hsgTpVAEGpJrFvnLrmDtsi6
    depends_on:
      - gopro-mysqldb
    restart: always